### ISSUE TITLE
关于黑苹果网卡

### ISSUE THREAD

**Issue by vibratea** [sqlsec/Asus-ChromeBox-i7-8550U#1]
请问大佬，你用的哪款网卡，能把店铺直接告之一下吗？或者什么型号的？谢谢

**Comment by jee1022** [comment]
请问大佬，4k显示细腻度怎么解决？

**Comment by sqlsec** [comment]
BCM94360CS2 闲鱼上拆机卡价格是 45元左右，再闲鱼上买个 10 块钱的转接卡就 OK 了，总成本 50 多块钱
