### ISSUE TITLE
请问有人知道这款机器（chromebox3cn65）的声卡是什么型号吗？

### ISSUE THREAD

**Issue by SoMeTech** [sqlsec/Asus-ChromeBox-i7-8550U#17]
在https://github.com/jingkunchen/Chromebox3-Sonoma-Hackintosh处看到说声卡是Realtek ALC255,不知道是否能够确认。如果可以的话，声卡也可以驱动。https://heipg.cn/tutorial/applealc-patch.html有方法，
有朋友试过吗？

**Comment by sqlsec** [comment]
我看这项目他驱动声卡了，你可以考虑直接用这个项目试试看。我最近工作和职业规划问题，黑苹果这块应该可能不碰了
